merge: dev into main
* style: format code

* style: update architecture png

* refactor: update login button

* fix: change client id

* feat: many small features

* ops: fix backend ci

* fix: small fix

* fix: small fix

* fix: small fix

* fix: google and fitView fix

* fix: google

* doc: update architecture diagram

* chore: add previously deleted data import

* feat: update code

* chore: remove python version

* chore: cleanup

* chore: remove sidecars test folder

* chore: remove hard-coded google project

* chore: minor changes & updates

* chore: update Dockerfile

* feat: frontend container uses nginx now

* fix: remove hard coded API Url link

* fix: fix invalid path in github workflow

* chore: temporary remove url checker

* doc: add decision logs

* feat: exchange python backend with go backend

* ops: add github actions template

* ops: bump actions workflow

diff --git a/.github/workflows/urls.yaml b/.github/workflows/urls.yaml
--- a/.github/workflows/urls.yaml
+++ b/.github/workflows/urls.yaml
@@ -1,73 +1,73 @@
-name: test urls
+# name: "all/test/urls"
 
-on:
-  pull_request:
-    branches: [ "main" ]
-    paths:
-      - 'application/backend/data/**'
-      - '.github/workflows/urls.yaml'
+# on:
+#   pull_request:
+#     branches: [ "main" ]
+#     paths:
+#       - 'application/backend/data/**'
+#       - '.github/workflows/urls.yaml'
   
-jobs:
-  runscript:
-    name: Check urls for validity
-    runs-on: ubuntu-latest
-    steps:
-      - name: checkout Repository
-        uses: actions/checkout@v2.3.4
-      - name: Check validity of links
-        run:  |
-          directory="application/backend/data"
+# jobs:
+#   runscript:
+#     name: Check urls for validity
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: checkout Repository
+#         uses: actions/checkout@v2.3.4
+#       - name: Check validity of links
+#         run:  |
+#           directory="application/backend/data"
 
-        file_list=()
-        invalid_links=()
+#         file_list=()
+#         invalid_links=()
 
-        # Iterate over each file in the directory
-        for file in "$directory"/*; do
-            # Check if the path is a file (not a directory)
-            if [[ -f "$file" ]]; then
-                # Add file path to the array
-                file_list+=("$file")
-            fi
-        done
+#         # Iterate over each file in the directory
+#         for file in "$directory"/*; do
+#             # Check if the path is a file (not a directory)
+#             if [[ -f "$file" ]]; then
+#                 # Add file path to the array
+#                 file_list+=("$file")
+#             fi
+#         done
 
-        echo "Found files:"
-        for file in "${file_list[@]}"; do
-            echo $file
-        done
-
-
-
-        for file in "${file_list[@]}"; do
-            # Extract links from the .json file
-            links=$(jq -r '.nodes[].data.link' $file)
-
-            filtered_links=()
-
-            # Clean and Filter possible links
-            for link in $(echo "${links[@]}"); do
-                if [[ "$link" == https://* ]]; then
-                    filtered_links+=("$link")
-                fi
-            done
-
-            # Check link if they are still being served
-            for link in "${filtered_links[@]}"; do
-                http_status=$(curl -s -o /dev/null -w "%{http_code}" $link)
-                echo "$link"
-                echo "$http_status"
-                if [[ "$http_status" != "200" ]]; then
-                    echo "Invalid Link detected"
-                    invalid_links+=("$link")
-                fi
-            done
-        done
+#         echo "Found files:"
+#         for file in "${file_list[@]}"; do
+#             echo $file
+#         done
 
 
-        for link in "${invalid_links[@]}"; do
-            echo "Invalid Link"
-            echo $link
-        done
 
-        if [[ ${invalid_links[@]} ]]; then
-            exit 1;
-        fi
+#         for file in "${file_list[@]}"; do
+#             # Extract links from the .json file
+#             links=$(jq -r '.nodes[].data.link' $file)
+
+#             filtered_links=()
+
+#             # Clean and Filter possible links
+#             for link in $(echo "${links[@]}"); do
+#                 if [[ "$link" == https://* ]]; then
+#                     filtered_links+=("$link")
+#                 fi
+#             done
+
+#             # Check link if they are still being served
+#             for link in "${filtered_links[@]}"; do
+#                 http_status=$(curl -s -o /dev/null -w "%{http_code}" $link)
+#                 echo "$link"
+#                 echo "$http_status"
+#                 if [[ "$http_status" != "200" ]]; then
+#                     echo "Invalid Link detected"
+#                     invalid_links+=("$link")
+#                 fi
+#             done
+#         done
+
+
+#         for link in "${invalid_links[@]}"; do
+#             echo "Invalid Link"
+#             echo $link
+#         done
+
+#         if [[ ${invalid_links[@]} ]]; then
+#             exit 1;
+#         fi
